### ISSUE TITLE
一则旧闻

### ISSUE THREAD

**Issue by ghost** [nonstop-story/privacy-stealers#1]
https://github.com/shadowsocks/shadowsocks-windows/issues/2162#issuecomment-455615758

**Comment by imkiva** [comment]
刚刚去 https://www.ringofelysiumonline.com/webprivacy.htm 看了一下，其中对 Shadowrocket 的那部分描述已经没有了

**Comment by ghost** [comment]
按照 wayback machine 的历史记录，这段描述于2019年4月-5月被移除
